version: "3"
services:
  db:
    image: mysql:5.7
    container_name: mysql-5.7
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: pyrodb
      MYSQL_USER: pyro
      MYSQL_PASSWORD: pyro1234
    ports:
      - "3306:3306"
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
      - ./db/conf:/etc/mysql/conf.d
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 9984:8080

  nginx:
    image: nginx:1.20
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
