# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'baseball' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for baseball
  pod 'RxSwift', '~> 6.1.0'
  pod 'RxCocoa', '~> 6.1.0'
  pod 'Alamofire', '~> 5.4.3'

  target 'baseballTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'baseballUITests' do
    # Pods for testing
  end

end
