# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Baseball' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 5.2'

  # Pods for Baseball

  target 'BaseballTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseballUITests' do
    # Pods for testing
  end

end
