-- MySQL Script generated by MySQL Workbench
-- Mon May 10 22:44:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema baseball
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema baseball
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baseball` DEFAULT CHARACTER SET utf8 ;
USE `baseball` ;

-- -----------------------------------------------------
-- Table `baseball`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseball`.`team` ;

CREATE TABLE IF NOT EXISTS `baseball`.`team` (
                                                 `id` INT NOT NULL AUTO_INCREMENT,
                                                 `name` VARCHAR(45) NOT NULL,
                                                 PRIMARY KEY (`id`),
                                                 UNIQUE INDEX `name_UNIQUE` (`name` ASC))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseball`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseball`.`game` ;

CREATE TABLE IF NOT EXISTS `baseball`.`game` (
                                                 `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                 `away_team_id` INT NOT NULL,
                                                 `home_team_id` INT NOT NULL,
                                                 `current_inning` INT NOT NULL,
                                                 `current_halves` VARCHAR(6) NOT NULL,
                                                 `pitcher_uniform_number` INT NOT NULL,
                                                 `batter_uniform_number` INT NOT NULL,
                                                 `base1_uniform_number` INT NULL,
                                                 `base2_uniform_number` INT NULL,
                                                 `base3_uniform_number` INT NULL,
                                                 `strike_count` INT NOT NULL,
                                                 `ball_count` INT NOT NULL,
                                                 `out_count` INT NOT NULL,
                                                 `status` VARCHAR(45) NOT NULL,
                                                 PRIMARY KEY (`id`),
                                                 INDEX `fk_game_team2_idx` (`away_team_id` ASC),
                                                 INDEX `fk_game_team1_idx` (`home_team_id` ASC),
                                                 CONSTRAINT `fk_game_team2`
                                                     FOREIGN KEY (`away_team_id`)
                                                         REFERENCES `baseball`.`team` (`id`)
                                                         ON DELETE NO ACTION
                                                         ON UPDATE NO ACTION,
                                                 CONSTRAINT `fk_game_team1`
                                                     FOREIGN KEY (`home_team_id`)
                                                         REFERENCES `baseball`.`team` (`id`)
                                                         ON DELETE NO ACTION
                                                         ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseball`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseball`.`user` ;

CREATE TABLE IF NOT EXISTS `baseball`.`user` (
                                                 `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                 `email` VARCHAR(45) NOT NULL,
                                                 `current_game_id` BIGINT NULL,
                                                 `current_game_venue` CHAR(4) NULL,
                                                 PRIMARY KEY (`id`),
                                                 INDEX `fk_user_game1_idx` (`current_game_id` ASC),
                                                 UNIQUE INDEX `email_UNIQUE` (`email` ASC),
                                                 CONSTRAINT `fk_user_game1`
                                                     FOREIGN KEY (`current_game_id`)
                                                         REFERENCES `baseball`.`game` (`id`)
                                                         ON DELETE NO ACTION
                                                         ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseball`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseball`.`player` ;

CREATE TABLE IF NOT EXISTS `baseball`.`player` (
                                                   `id` INT NOT NULL AUTO_INCREMENT,
                                                   `team_id` INT NOT NULL,
                                                   `name` VARCHAR(45) NOT NULL,
                                                   `uniform_number` INT NOT NULL,
                                                   INDEX `fk_player_team_idx` (`team_id` ASC),
                                                   PRIMARY KEY (`id`),
                                                   CONSTRAINT `fk_player_team`
                                                       FOREIGN KEY (`team_id`)
                                                           REFERENCES `baseball`.`team` (`id`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseball`.`inning`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseball`.`inning` ;

CREATE TABLE IF NOT EXISTS `baseball`.`inning` (
                                                   `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                   `game_id` BIGINT NOT NULL,
                                                   `inning` INT NOT NULL,
                                                   `halves` VARCHAR(6) NOT NULL,
                                                   `score` INT NOT NULL,
                                                   `key_in_game` VARCHAR(10) NOT NULL,
                                                   PRIMARY KEY (`id`),
                                                   INDEX `fk_score_game1_idx` (`game_id` ASC),
                                                   CONSTRAINT `fk_score_game1`
                                                       FOREIGN KEY (`game_id`)
                                                           REFERENCES `baseball`.`game` (`id`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseball`.`pitch_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseball`.`pitch_history` ;

CREATE TABLE IF NOT EXISTS `baseball`.`pitch_history` (
                                                          `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                          `inning_id` BIGINT NOT NULL,
                                                          `pitcher_team_id` INT NOT NULL,
                                                          `pitcher_uniform_number` INT NOT NULL,
                                                          `batter_team_id` INT NOT NULL,
                                                          `batter_uniform_number` INT NOT NULL,
                                                          `result` VARCHAR(6) NOT NULL,
                                                          `index_in_inning` INT NOT NULL,
                                                          `strike_count` INT NOT NULL,
                                                          `ball_count` INT NOT NULL,
                                                          PRIMARY KEY (`id`),
                                                          INDEX `fk_history_inning1_idx` (`inning_id` ASC),
                                                          INDEX `fk_pitch_history_team1_idx` (`pitcher_team_id` ASC),
                                                          INDEX `fk_pitch_history_team2_idx` (`batter_team_id` ASC),
                                                          CONSTRAINT `fk_history_inning1`
                                                              FOREIGN KEY (`inning_id`)
                                                                  REFERENCES `baseball`.`inning` (`id`)
                                                                  ON DELETE NO ACTION
                                                                  ON UPDATE NO ACTION,
                                                          CONSTRAINT `fk_pitch_history_team1`
                                                              FOREIGN KEY (`pitcher_team_id`)
                                                                  REFERENCES `baseball`.`team` (`id`)
                                                                  ON DELETE NO ACTION
                                                                  ON UPDATE NO ACTION,
                                                          CONSTRAINT `fk_pitch_history_team2`
                                                              FOREIGN KEY (`batter_team_id`)
                                                                  REFERENCES `baseball`.`team` (`id`)
                                                                  ON DELETE NO ACTION
                                                                  ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseball`.`batting_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseball`.`batting_history` ;

CREATE TABLE IF NOT EXISTS `baseball`.`batting_history` (
                                                            `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                            `game_id` BIGINT NOT NULL,
                                                            `batter_team_id` INT NOT NULL,
                                                            `batter_uniform_number` INT NOT NULL,
                                                            `appear` INT NOT NULL,
                                                            `hits` INT NOT NULL,
                                                            `out` INT NOT NULL,
                                                            `key_in_game` VARCHAR(45) NOT NULL,
                                                            PRIMARY KEY (`id`),
                                                            INDEX `fk_batting_history_game1_idx` (`game_id` ASC),
                                                            INDEX `fk_batting_history_team1_idx` (`batter_team_id` ASC),
                                                            CONSTRAINT `fk_batting_history_game1`
                                                                FOREIGN KEY (`game_id`)
                                                                    REFERENCES `baseball`.`game` (`id`)
                                                                    ON DELETE NO ACTION
                                                                    ON UPDATE NO ACTION,
                                                            CONSTRAINT `fk_batting_history_team1`
                                                                FOREIGN KEY (`batter_team_id`)
                                                                    REFERENCES `baseball`.`team` (`id`)
                                                                    ON DELETE NO ACTION
                                                                    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseball`.`oauth_access_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseball`.`oauth_access_token` ;

CREATE TABLE IF NOT EXISTS `baseball`.`oauth_access_token` (
                                                               `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                               `user_id` BIGINT NOT NULL,
                                                               `resource_server` VARCHAR(45) NOT NULL,
                                                               `access_token` VARCHAR(100) NOT NULL,
                                                               PRIMARY KEY (`id`),
                                                               INDEX `fk_oauth_access_token_user1_idx` (`user_id` ASC),
                                                               INDEX `uk_user_id_resource_owner` (`user_id` ASC, `resource_server` ASC),
                                                               CONSTRAINT `fk_oauth_access_token_user1`
                                                                   FOREIGN KEY (`user_id`)
                                                                       REFERENCES `baseball`.`user` (`id`)
                                                                       ON DELETE NO ACTION
                                                                       ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
