const gameDatas = [
  {
    id: 1,
    homeTeamName: "KIA 타이거즈",
    awayTeamName: "NC 다이노즈",
  },
  {
    id: 2,
    homeTeamName: "삼성 라이온즈",
    awayTeamName: "한화 이글스",
  },
  {
    id: 3,
    homeTeamName: "두산 베어스",
    awayTeamName: "롯데 자이언츠",
  },
  {
    id: 4,
    homeTeamName: "SSG 랜더스",
    awayTeamName: "LG 트윈스",
  },
  {
    id: 5,
    homeTeamName: "키움 히어로즈",
    awayTeamName: "kt wiz",
  },
];

const GAME1 = {
  gameId: 1,
  home: [
    {
      id: 1,
      name: "김선빈",
      position: "타자",
      atBat: 0,
      hit: 0,
      out: 0,
      average: 0,
    },
    {
      id: 2,
      name: "김태진",
      position: "타자",
      atBat: 0,
      hit: 0,
      out: 0,
      average: 0,
    },
    {
      id: 3,
      name: "박정우",
      position: "타자",
      atBat: 0,
      hit: 0,
      out: 0,
      average: 0,
    },
    {
      id: 4,
      name: "최원준",
      position: "타자",
      atBat: 0,
      hit: 0,
      out: 0,
      average: 0,
    },
    {
      id: 5,
      name: "최형우",
      position: "타자",
      atBat: 0,
      hit: 0,
      out: 0,
      average: 0,
    },
    {
      id: 6,
      name: "이진영",
      position: "타자",
      atBat: 0,
      hit: 0,
      out: 0,
      average: 0,
    },
    {
      id: 7,
      name: "나지완",
      position: "타자",
      atBat: 3,
      hit: 3,
      out: 1,
      average: 0,
    },
    {
      id: 8,
      name: "이창진",
      position: "타자",
      atBat: 5,
      hit: 2,
      out: 3,
      average: 0,
    },
    {
      id: 9,
      name: "김유신",
      position: "투수",
      atBat: 0,
      hit: 0,
      out: 0,
      average: 0,
    },
  ],
  away: [
    {
      id: 10,
      name: "박민우",
      position: "타자",
      atBat: 0,
      hit: 0,
      out: 0,
      average: 0,
    },
    {
      id: 11,
      name: "김민수",
      position: "타자",
      atBat: 0,
      hit: 0,
      out: 0,
      average: 0,
    },
    {
      id: 12,
      name: "박석민",
      position: "타자",
      atBat: 0,
      hit: 0,
      out: 0,
      average: 0,
    },
    {
      id: 13,
      name: "나성범",
      position: "타자",
      atBat: 0,
      hit: 0,
      out: 0,
      average: 0,
    },
    {
      id: 14,
      name: "이명기",
      position: "타자",
      atBat: 0,
      hit: 0,
      out: 0,
      average: 0,
    },
    {
      id: 15,
      name: "구창모",
      position: "투수",
      atBat: 0,
      hit: 0,
      out: 0,
      average: 0,
    },
    {
      id: 16,
      name: "애런 알테어",
      position: "타자",
      atBat: 0,
      hit: 0,
      out: 0,
      average: 0,
    },
    {
      id: 17,
      name: "모창민",
      position: "타자",
      atBat: 0,
      hit: 0,
      out: 0,
      average: 0,
    },
    {
      id: 18,
      name: "박준영",
      position: "타자",
      atBat: 0,
      hit: 0,
      out: 0,
      average: 0,
    },
  ],
};

export { gameDatas, GAME1 };
