INSERT INTO `baseball`.`team` (`team_id`, `name`, `isPlaying`) VALUES ('1', 'Samsung Lions', '0');
INSERT INTO `baseball`.`team` (`team_id`, `name`, `isPlaying`) VALUES ('2', 'KIA Tigers', '1');
INSERT INTO `baseball`.`team` (`team_id`, `name`, `isPlaying`) VALUES ('3', 'NC Dinos', '0');
INSERT INTO `baseball`.`team` (`team_id`, `name`, `isPlaying`) VALUES ('4', 'Hanwha Eagles', '0');
INSERT INTO `baseball`.`team` (`team_id`, `name`, `isPlaying`) VALUES ('5', 'Lotte Giants', '1');
INSERT INTO `baseball`.`team` (`team_id`, `name`, `isPlaying`) VALUES ('6', 'Doosan Bears', '0');
INSERT INTO `baseball`.`team` (`team_id`, `name`, `isPlaying`) VALUES ('7', 'SSG Landers', '0');
INSERT INTO `baseball`.`team` (`team_id`, `name`, `isPlaying`) VALUES ('8', 'LG Twins', '0');

INSERT INTO `baseball`.`player` (`player_id`, `number`, `name`, `pa`, `hit`, `out`, `average`, `team_id`) VALUES ('1', '1', '강민호', '0', '0', '0', '0.0', '1');
INSERT INTO `baseball`.`player` (`player_id`, `number`, `name`, `pa`, `hit`, `out`, `average`, `team_id`) VALUES ('2', '2', '강한울', '0', '0', '0', '0.0', '1');
INSERT INTO `baseball`.`player` (`player_id`, `number`, `name`, `pa`, `hit`, `out`, `average`, `team_id`) VALUES ('3', '3', '구자욱', '0', '0', '0', '0.0', '1');
INSERT INTO `baseball`.`player` (`player_id`, `number`, `name`, `pa`, `hit`, `out`, `average`, `team_id`) VALUES ('4', '4', '김상수', '0', '0', '0', '0.0', '1');
INSERT INTO `baseball`.`player` (`player_id`, `number`, `name`, `pa`, `hit`, `out`, `average`, `team_id`) VALUES ('5', '5', '김성윤', '0', '0', '0', '0.0', '1');
INSERT INTO `baseball`.`player` (`player_id`, `number`, `name`, `pa`, `hit`, `out`, `average`, `team_id`) VALUES ('6', '6', '김현곤', '0', '0', '0', '0.0', '1');
INSERT INTO `baseball`.`player` (`player_id`, `number`, `name`, `pa`, `hit`, `out`, `average`, `team_id`) VALUES ('7', '7', '박해민', '0', '0', '0', '0.0', '1');
INSERT INTO `baseball`.`player` (`player_id`, `number`, `name`, `pa`, `hit`, `out`, `average`, `team_id`) VALUES ('8', '8', '라이블리', '0', '0', '0', '0.0', '1');
INSERT INTO `baseball`.`player` (`player_id`, `number`, `name`, `pa`, `hit`, `out`, `average`, `team_id`) VALUES ('9', '9', '오승환', '0', '0', '0', '0.0', '1');
INSERT INTO `baseball`.`player` (`player_id`, `number`, `name`, `pa`, `hit`, `out`, `average`, `team_id`) VALUES ('10', '1', '고영창', '0', '0', '0', '0.0', '2');
INSERT INTO `baseball`.`player` (`player_id`, `number`, `name`, `pa`, `hit`, `out`, `average`, `team_id`) VALUES ('11', '2', '권혁경', '0', '0', '0', '0.0', '2');
INSERT INTO `baseball`.`player` (`player_id`, `number`, `name`, `pa`, `hit`, `out`, `average`, `team_id`) VALUES ('12', '3', '김규성', '0', '0', '0', '0.0', '2');
INSERT INTO `baseball`.`player` (`player_id`, `number`, `name`, `pa`, `hit`, `out`, `average`, `team_id`) VALUES ('13', '4', '김원경', '0', '0', '0', '0.0', '2');
INSERT INTO `baseball`.`player` (`player_id`, `number`, `name`, `pa`, `hit`, `out`, `average`, `team_id`) VALUES ('14', '5', '나주환', '0', '0', '0', '0.0', '2');
INSERT INTO `baseball`.`player` (`player_id`, `number`, `name`, `pa`, `hit`, `out`, `average`, `team_id`) VALUES ('15', '6', '박건우', '0', '0', '0', '0.0', '2');
INSERT INTO `baseball`.`player` (`player_id`, `number`, `name`, `pa`, `hit`, `out`, `average`, `team_id`) VALUES ('16', '7', '박찬호', '0', '0', '0', '0.0', '2');
INSERT INTO `baseball`.`player` (`player_id`, `number`, `name`, `pa`, `hit`, `out`, `average`, `team_id`) VALUES ('17', '8', '브룩스', '0', '0', '0', '0.0', '2');
INSERT INTO `baseball`.`player` (`player_id`, `number`, `name`, `pa`, `hit`, `out`, `average`, `team_id`) VALUES ('18', '9', '양승철', '0', '0', '0', '0.0', '2');
